name: adpro
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - anyio=4.2.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.18.1
  - executing=0.8.3
  - flake8=6.1.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.4
  - httpx=0.27.0
  - hyperframe=6.0.1
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=7.0.2
  - importlib_metadata=7.0.2
  - importlib_resources=6.1.3
  - iniconfig=1.1.1
  - ipykernel=6.28.0
  - ipython=8.20.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.1.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mistune=2.0.4
  - munkres=1.1.4
  - mypy=1.5.1
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=7.1.1
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.3.0
  - openssl=3.2.1
  - overrides=7.4.0
  - pandas=2.1.4
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pep8=1.7.1
  - pexpect=4.8.0
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.11.1
  - pycparser=2.21
  - pyflakes=3.1.0
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - soupsieve=2.5
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=1.26.18
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - dataclasses-json==0.6.4
      - distro==1.9.0
      - dnspython==2.6.1
      - email-validator==2.1.0.post1
      - fiona==1.9.5
      - frozenlist==1.4.1
      - fuzzywuzzy==0.18.0
      - geopandas==0.14.3
      - jsonpatch==1.33
      - jsonpointer==2.4
      - langchain==0.1.11
      - langchain-community==0.0.27
      - langchain-core==0.1.30
      - langchain-openai==0.0.8
      - langchain-text-splitters==0.0.1
      - langsmith==0.1.23
      - marshmallow==3.21.1
      - multidict==6.0.5
      - openai==1.13.3
      - orjson==3.9.15
      - packaging==23.2
      - pydantic==2.0.3
      - pydantic-core==2.3.0
      - pyproj==3.6.1
      - python-dotenv==1.0.1
      - regex==2023.12.25
      - seaborn==0.13.2
      - shapely==2.0.3
      - sqlalchemy==2.0.28
      - tenacity==8.2.3
      - tiktoken==0.6.0
      - tqdm==4.66.2
      - typing-inspect==0.9.0
      - yarl==1.9.4
